# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eprotocol.proto\x12\x0cprotocol_pb2\"~\n\x08Protocol\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x0b\n\x03src\x18\x03 \x01(\t\x12\x0b\n\x03\x64st\x18\x04 \x01(\t\x12,\n\tdirective\x18\x05 \x01(\x0b\x32\x17.protocol_pb2.DirectiveH\x00\x42\x06\n\x04\x64\x61ta\"\xca\x01\n\tDirective\x12\x0e\n\x06msg_id\x18\x01 \x01(\t\x12\x11\n\tdirective\x18\x02 \x01(\t\x12\x0e\n\x06target\x18\x03 \x01(\t\x12\x42\n\x0e\x64irective_args\x18\x04 \x03(\x0b\x32*.protocol_pb2.Directive.DirectiveArgsEntry\x12\x10\n\x08modem_id\x18\x05 \x01(\t\x1a\x34\n\x12\x44irectiveArgsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DIRECTIVE_DIRECTIVEARGSENTRY._options = None
  _DIRECTIVE_DIRECTIVEARGSENTRY._serialized_options = b'8\001'
  _globals['_PROTOCOL']._serialized_start=32
  _globals['_PROTOCOL']._serialized_end=158
  _globals['_DIRECTIVE']._serialized_start=161
  _globals['_DIRECTIVE']._serialized_end=363
  _globals['_DIRECTIVE_DIRECTIVEARGSENTRY']._serialized_start=311
  _globals['_DIRECTIVE_DIRECTIVEARGSENTRY']._serialized_end=363
# @@protoc_insertion_point(module_scope)
